### ISSUE TITLE
Error: "has conflicts" label not found in your repository!

### ISSUE THREAD

**Issue by splincode** [mschilde/auto-label-merge-conflicts#52]
Please auto create `has conflicts` 
if repo doesn't have custom lable

**Comment by ykws** [comment]
Same here.
Today, we encountered the same issue.

```
Error: "has conflicts" label not found in your repository!
/home/autolabel/dist/lib/main.js:71
                return label.node.id === conflictLabel.node.id;
                                                       ^

TypeError: Cannot read properties of undefined (reading 'node')
    at /home/autolabel/dist/lib/main.js:71:56
    at Array.find (<anonymous>)
    at /home/autolabel/dist/lib/main.js:70:68
    at Array.forEach (<anonymous>)
    at Object.run (/home/autolabel/dist/lib/main.js:69:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/autolabel/dist/index.js:5:5
```

We resolved it by changing the label name from “has conflicts” to **“conflicts”**.
It seems that `node.id` must **not include spaces**.

If you need any more adjustments, feel free to let me know!

**Comment by jrfnl** [comment]
I'm seeing the same problem as of today with a label name of "Status: has merge conflict" (and I'd really prefer not to have to change the label name).

I'm also seeing a deprecation notice. Could this be related ?

```
(node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by NxSoftware** [comment]
+1 for the label not found issue.

```
Error: "has conflicts" label not found in your repository!
/home/autolabel/dist/lib/main.js:71
                return label.node.id === conflictLabel.node.id;
```

**Comment by ykws** [comment]
@jrfnl @NxSoftware Workaround: Exclude spaces or replace them with underscores.

For example, rename "has conflicts" to:

- conflicts
- has_conflicts

Best regards.

**Comment by ykws** [comment]
I recommend the following action as well. It allows labeling even if the label name includes spaces.

https://github.com/eps1lon/actions-label-merge-conflict

- refs: https://github.com/mschilde/auto-label-merge-conflicts/issues/54#issuecomment-1934976753

**Comment by jrfnl** [comment]
@ykws I've switched to `eps1lon/actions-label-merge-conflict` as well for now.
